### PR TITLE
Go module, fix misspells, add Iris integration

### PR DESCRIPTION
**Pull request by kataras**
## Goal

 - Add a `go.mod` file (`go.sum` is not pushed, you can do it when you feel safe with go modules).

- Add Iris integration as requested at: https://github.com/kataras/iris/issues/1550.

Fix some misspells too.

### Added

go.mod
/iris
/examples/iris
/features/iris_features

## Tests

iris/iris_test.go

## Discussion

https://github.com/kataras/iris/issues/1550.

## What's missing

A CHANGELOG.md entry, you can just add "add iris integration" when you release your next version.

### CODE REVIEW

**Comment by xander-jones** [comment]
Hi @kataras, thanks for the PR. We will review this when priorities allow.

**Comment by kataras** [comment]
Yes @xander-jones,  no worries I see that. Your team needs to update the docs on the website too (gin is missing from there too as I remember) and also the minimum go version required should change. If you need anything from me please don't hesitate to ask, I am available to help with all my powers

**Comment by kattrali** [comment]
Thanks for the contribution, we are planning to handle module support (and general fixes) separately. Iris support is not being added at this time. Ideally new framework support should be in separate repositories, to avoid indirect dependencies on every framework.

**Comment by kataras** [comment]
I see @kattrali, let me know if you need my help.

**Pull request closed without merging**
