### PR TITLE
Sanitize should also handler json and []byte

### PR DESCRIPTION
**Pull request by veqryn**
## Goal
We log in json, and send details and types to both our logger and also to bugsnag that are json.RawMessage, have a MarshalJSON method, or are byte slices.

## Design
Good place for it.

## Changeset
See PR.

## Testing
Added test cases to cover the new functionality.

### CODE REVIEW

**Comment by DariaKunoichi** [comment]
@veqryn Hi, thanks for preparing a PR.

- [ ] Can I ask you to add more unit testing around edge cases?
- [ ] Also, please change the branch you want to merge to from `master` to `next` as this is our release process.

After you add it I will try authorizing the CI so maybe I won't have to cherry pick your commits into another PR.

**Comment by veqryn** [comment]
Sure. Do you have any edge cases in mind?

**Comment by DariaKunoichi** [comment]
Nil pointers check for sure, like we do [here](https://github.com/bugsnag/bugsnag-go/blob/master/v2/metadata_test.go#L113).
And maybe try nesting them in a map? Like [here](https://github.com/bugsnag/bugsnag-go/blob/master/v2/metadata_test.go#L115).

**Comment by veqryn** [comment]
@DariaKunoichi done

**Review by DariaKunoichi — APPROVED** [review]

**Comment by mclack** [comment]
Hi @veqryn 

Thanks for your contributions here. This has now been added in our [v2.4.0 release](https://github.com/bugsnag/bugsnag-go/releases/tag/v2.4.0).

**Pull request merged**
