### PR TITLE
Support app.type in error events

### PR DESCRIPTION
**Pull request by jaschaephraim**

### CODE REVIEW

**Comment by montanaflynn** [comment]
Paging Dr. @gkze, can we get a merge?

**Comment by gkze** [comment]
What is the use case for this? That is not part of our default schema. You can send this as [custom metadata](https://docs.bugsnag.com/platforms/go/other/#sending-diagnostic-data) and create a [custom filter](https://docs.bugsnag.com/product/custom-filters/) on it.

**Comment by jaschaephraim** [comment]
I believe it is part of the event schema: https://docs.bugsnag.com/api/error-reporting/ . This allows sorting under the App Types tab in Timeline.

**Comment by montanaflynn** [comment]
The use case is to get our app types to show up in bugsnag so we can filter by them:

screen shot 2017-06-30 at 11 11 35 am

It appears to be included in the default schema listed here: https://docs.bugsnag.com/api/error-reporting/#library-configuration

```
        // Information about the app that crashed.
        // These fields are optional but highly recommended
        "app": {
          // The version number of the application which generated the error.
          // If appVersion is set and an error is resolved in the dashboard
          // the error will not unresolve until a crash is seen in a newer
          // version of the app.
          // (optional, default none, filtered)
          "version": "1.1.3",

          // The release stage that this error occurred in, for example
          // "development", "staging" or "production".
          // (optional, default "production", filtered)
          "releaseStage": "production",

          // A specialized type of the application, such as the worker queue or web
          // framework used, like "rails", "mailman", or "celery"
          "type": "rails"
        },
```

**Comment by kattrali** [comment]
Thanks for the contribution, @jaschaephraim. Looks good. It seems app type was overlooked when setting up the configuration for the library. I'm drafting a change to the docs and then will release this. 👍

**Comment by kattrali** [comment]
Updated: https://docs.bugsnag.com/platforms/go/other/configuration-options/#apptype

**Pull request merged**
